# About
title: JSON generator for privacy notices
description: Help turn privacy policies into structured data
url: https://rightsbase.projectsbyif.com

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png

# Social media
use_facebook_meta_tags: false
use_twitter_meta_tags: false
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_handle: @projectsbyif

# Config
data_repository: https://github.com/projectsbyif/open-data-rights-data/
